#!/bin/sh
sudo apt-get update
sudo apt-get install -y default-jre 
sudo apt-get install -y unzip 
sudo apt-get install -y libutfcpp-dev 
sudo apt-get install -y cmake 
sudo apt-get install -y curl
sudo apt-get install -y git
