name: 'Build Modified Postgres'

runs:
  using: "composite"
  steps:
    - name: Build Modified Postgres
      id: build-modified-postgres
      run: |
        # Function to compare versions correctly
        version_le() {
          printf "%s\n%s" "$1" "$2" | sort -V | head -n1 | grep -q "^$1$"
        }
        # Use gcc-9 for versions prior to 14.18, 15.13, 16.9 and 17.5
        engine_version="${{ inputs.engine_version }}"
        if [[ "$engine_version" != "source.latest" && "$engine_version" != "target.latest" ]] && 
          ( version_le "$engine_version" "14.17" || 
            ( [[ "${engine_version%%.*}" == "15" ]] && version_le "$engine_version" "15.12" ) || 
            ( [[ "${engine_version%%.*}" == "16" ]] && version_le "$engine_version" "16.8" ) || 
            ( [[ "${engine_version%%.*}" == "17" ]] && version_le "$engine_version" "17.4" ) ); then
          export CC='ccache gcc-9'
        else
          export CC='ccache gcc'
        fi

        cd ${{ env.PG_SRC }}
        ./configure --prefix=${{env.BABELFISH_HOME}}/ CFLAGS="-ggdb" --enable-debug --with-ldap --with-libxml --with-pam  --with-uuid=ossp  --enable-nls --with-libxslt --with-icu
        make DESTDIR=${{env.BABELFISH_HOME}} -j $JOBS 2>error.txt
        sudo make install
        cd contrib && make -j ${JOBS} && sudo make install
      shell: bash