#!/bin/bash

DEFAULT_DISTRO="ubuntu"
DEFAULT_OSVERSION="focal"
DEFAULT_ANTLR_VERSION="4.9.3"


function help() { 
    echo "
        -T Babelfish tag, in the form of BABEL_2_1_1__PG_14_3 as eg. Mandatory.
        -o Operating System. Default: ubuntu
        -v Operating System version (eg. focal, bullseye, 8, etc.). Default: focal
        -a Antlr Version. Default: 4.9.3
    "
}

while getopts 'o:v:T:a:h' OPT
do
    case "$OPT" in
        o)    DISTRO=$OPTARG ;;
        v)    OSVERSION=$OPTARG ;;
        T)    export TAG=$OPTARG ;;
        a)    ANTLR_VERSION=$OPTARG ;;
        h|--help) help ;;
        *)    help ; exit 1 ;;
    esac
done


shift $(($OPTIND - 1))

if [ ! -v TAG ]
then
    printf "TAG is a mandatory argument (-T).\n"
    help
    exit 2
fi

export DISTRO=${DISTRO:-$DEFAULT_DISTRO}
export OSVERSION=${OSVERSION:-$DEFAULT_OSVERSION}
export ANTLR_VERSION=${ANTLR_VERSION:-$DEFAULT_ANTLR_VERSION}

export BABELFISH_VERSION=$(echo $TAG | sed -r -e 's/BABEL_([0-9a-z_]*)__PG.*/\1/' -e 's/_/./g')

export WARNING_QUOTE="
#
# Autogenerated files, do not edit. See README.md
#
"

mkdir -p ${BABELFISH_VERSION}/${DISTRO}/${OSVERSION}

j2 templates/${DISTRO}/${OSVERSION}/Dockerfile.j2 > ${BABELFISH_VERSION}/${DISTRO}/${OSVERSION}/Dockerfile
j2 templates/docker-compose.yml.j2 > ${BABELFISH_VERSION}/${DISTRO}/${OSVERSION}/docker-compose.yml
cp templates/entrypoint.sh ${BABELFISH_VERSION}/${DISTRO}/${OSVERSION}/entrypoint.sh