#!/bin/sh
sudo apt-get update
sudo apt-get install -y apt-utils 
sudo apt-get install -y build-essential flex libxml2-dev bison libreadline-dev zlib1g-dev
sudo apt-get install -y uuid-dev pkg-config libossp-uuid-dev libssl-dev icu-devtools
sudo apt-get install -y wget
